; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:freenove_esp32_s3_wroom]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/53.03.10/platform-espressif32.zip
platform_packages =
  espressif/toolchain-xtensa-esp32s3
#board = esp32-s3-devkitc-1
board = esp32-s3-devkitc-1-n16r8v
board_build.filesystem = littlefs
framework = arduino
lib_deps = robtillaart/INA226@^0.6.0
build_unflags = 
    -std=gnu++11
    -std=gnu++17
build_flags =
   -DARDUINO_USB_MODE=1
   -DARDUINO_USB_CDC_ON_BOOT=1
   -std=gnu++20
upload_port = /dev/cu.usbmodem101
monitor_port = /dev/cu.usbmodem101
monitor_speed = 115200
monitor_rts = 0
monitor_dtr = 0
; 1. Flash the initial sketch with these items commented out
; 2. Uncomment them for subsequent Wi-Fi uploads
; upload_protocol = espota
; upload_port = 192.168.50.142
; upload_flags = -apa44word123
;     --host_ip=192.168.50.122
;     --host_port=3232

;to upload run the following command in a terminal window outside of VSCode:
; python3 /Users/craig/.platformio/packages/framework-arduinoespressif32/tools/espota.py -i 192.168.50.142 -I 192.168.50.122 --auth=pa44word123 -f .pio/build/freenove_esp32_s3_wroom/firmware.bin
